### ISSUE TITLE
[T2] Create Test for VideoCassetteService

### ISSUE THREAD

**Issue by Bartek2463** [Bartek2463/video-app1011#2]

**Comment by JohnnHere** [comment]
Could you provide more information ? What kind of tests ?

**Comment by Bartek2463** [comment]
I write simple tests for video, I try use Junit, Asseration, mocktio .
Actual  I do develop tests, using adnotiation @Mock and @InjectMock.

pt., 7 paź 2022 o 04:49 João Orlando ***@***.***> napisał(a):

**Comment by JohnnHere** [comment]
And do you want some help ?

**Comment by Bartek2463** [comment]
No thanks, but it's nice that you offer to help.

pt., 7 paź 2022 o 16:40 João Orlando ***@***.***> napisał(a):
